version: '3.9'
services:
  bull-monitor:
    image: saade/bull-monitor
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_QUEUES: niveis,jobs
